// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: me/trinopoty/protobufRpc/codec/WirePacket.proto

package me.trinopoty.protobufRpc.codec;

public final class WirePacketFormat {
  private WirePacketFormat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code me.trinopoty.protobufRpc.codec.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MESSAGE_TYPE_NONE = 0;</code>
     */
    MESSAGE_TYPE_NONE(0),
    /**
     * <code>MESSAGE_TYPE_REQUEST = 1;</code>
     */
    MESSAGE_TYPE_REQUEST(1),
    /**
     * <code>MESSAGE_TYPE_RESPONSE = 2;</code>
     */
    MESSAGE_TYPE_RESPONSE(2),
    /**
     * <code>MESSAGE_TYPE_ERROR = 3;</code>
     */
    MESSAGE_TYPE_ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MESSAGE_TYPE_NONE = 0;</code>
     */
    public static final int MESSAGE_TYPE_NONE_VALUE = 0;
    /**
     * <code>MESSAGE_TYPE_REQUEST = 1;</code>
     */
    public static final int MESSAGE_TYPE_REQUEST_VALUE = 1;
    /**
     * <code>MESSAGE_TYPE_RESPONSE = 2;</code>
     */
    public static final int MESSAGE_TYPE_RESPONSE_VALUE = 2;
    /**
     * <code>MESSAGE_TYPE_ERROR = 3;</code>
     */
    public static final int MESSAGE_TYPE_ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return MESSAGE_TYPE_NONE;
        case 1: return MESSAGE_TYPE_REQUEST;
        case 2: return MESSAGE_TYPE_RESPONSE;
        case 3: return MESSAGE_TYPE_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:me.trinopoty.protobufRpc.codec.MessageType)
  }

  public interface ServiceIdentifierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 serviceIdentifier = 1;</code>
     */
    int getServiceIdentifier();

    /**
     * <code>int32 methodIdentifier = 2;</code>
     */
    int getMethodIdentifier();
  }
  /**
   * Protobuf type {@code me.trinopoty.protobufRpc.codec.ServiceIdentifier}
   */
  public  static final class ServiceIdentifier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
      ServiceIdentifierOrBuilder {
    // Use ServiceIdentifier.newBuilder() to construct.
    private ServiceIdentifier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceIdentifier() {
      serviceIdentifier_ = 0;
      methodIdentifier_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServiceIdentifier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              serviceIdentifier_ = input.readInt32();
              break;
            }
            case 16: {

              methodIdentifier_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder.class);
    }

    public static final int SERVICEIDENTIFIER_FIELD_NUMBER = 1;
    private int serviceIdentifier_;
    /**
     * <code>int32 serviceIdentifier = 1;</code>
     */
    public int getServiceIdentifier() {
      return serviceIdentifier_;
    }

    public static final int METHODIDENTIFIER_FIELD_NUMBER = 2;
    private int methodIdentifier_;
    /**
     * <code>int32 methodIdentifier = 2;</code>
     */
    public int getMethodIdentifier() {
      return methodIdentifier_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serviceIdentifier_ != 0) {
        output.writeInt32(1, serviceIdentifier_);
      }
      if (methodIdentifier_ != 0) {
        output.writeInt32(2, methodIdentifier_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serviceIdentifier_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serviceIdentifier_);
      }
      if (methodIdentifier_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, methodIdentifier_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier)) {
        return super.equals(obj);
      }
      me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier other = (me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier) obj;

      boolean result = true;
      result = result && (getServiceIdentifier()
          == other.getServiceIdentifier());
      result = result && (getMethodIdentifier()
          == other.getMethodIdentifier());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVICEIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getServiceIdentifier();
      hash = (37 * hash) + METHODIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getMethodIdentifier();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.trinopoty.protobufRpc.codec.ServiceIdentifier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder.class);
      }

      // Construct using me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serviceIdentifier_ = 0;

        methodIdentifier_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getDefaultInstanceForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance();
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier build() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier buildPartial() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier result = new me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier(this);
        result.serviceIdentifier_ = serviceIdentifier_;
        result.methodIdentifier_ = methodIdentifier_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier) {
          return mergeFrom((me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier other) {
        if (other == me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance()) return this;
        if (other.getServiceIdentifier() != 0) {
          setServiceIdentifier(other.getServiceIdentifier());
        }
        if (other.getMethodIdentifier() != 0) {
          setMethodIdentifier(other.getMethodIdentifier());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serviceIdentifier_ ;
      /**
       * <code>int32 serviceIdentifier = 1;</code>
       */
      public int getServiceIdentifier() {
        return serviceIdentifier_;
      }
      /**
       * <code>int32 serviceIdentifier = 1;</code>
       */
      public Builder setServiceIdentifier(int value) {
        
        serviceIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serviceIdentifier = 1;</code>
       */
      public Builder clearServiceIdentifier() {
        
        serviceIdentifier_ = 0;
        onChanged();
        return this;
      }

      private int methodIdentifier_ ;
      /**
       * <code>int32 methodIdentifier = 2;</code>
       */
      public int getMethodIdentifier() {
        return methodIdentifier_;
      }
      /**
       * <code>int32 methodIdentifier = 2;</code>
       */
      public Builder setMethodIdentifier(int value) {
        
        methodIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 methodIdentifier = 2;</code>
       */
      public Builder clearMethodIdentifier() {
        
        methodIdentifier_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
    }

    // @@protoc_insertion_point(class_scope:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
    private static final me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier();
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceIdentifier>
        PARSER = new com.google.protobuf.AbstractParser<ServiceIdentifier>() {
      public ServiceIdentifier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServiceIdentifier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceIdentifier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceIdentifier> getParserForType() {
      return PARSER;
    }

    public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WirePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.trinopoty.protobufRpc.codec.WirePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 messageIdentifier = 1;</code>
     */
    long getMessageIdentifier();

    /**
     * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
     */
    int getMessageTypeValue();
    /**
     * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
     */
    me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType getMessageType();

    /**
     * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    boolean hasServiceIdentifier();
    /**
     * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getServiceIdentifier();
    /**
     * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder getServiceIdentifierOrBuilder();

    /**
     * <code>bytes payload = 16;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code me.trinopoty.protobufRpc.codec.WirePacket}
   */
  public  static final class WirePacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.trinopoty.protobufRpc.codec.WirePacket)
      WirePacketOrBuilder {
    // Use WirePacket.newBuilder() to construct.
    private WirePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WirePacket() {
      messageIdentifier_ = 0L;
      messageType_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WirePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              messageIdentifier_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 90: {
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder subBuilder = null;
              if (serviceIdentifier_ != null) {
                subBuilder = serviceIdentifier_.toBuilder();
              }
              serviceIdentifier_ = input.readMessage(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serviceIdentifier_);
                serviceIdentifier_ = subBuilder.buildPartial();
              }

              break;
            }
            case 130: {

              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.Builder.class);
    }

    public static final int MESSAGEIDENTIFIER_FIELD_NUMBER = 1;
    private long messageIdentifier_;
    /**
     * <code>int64 messageIdentifier = 1;</code>
     */
    public long getMessageIdentifier() {
      return messageIdentifier_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
     */
    public me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType getMessageType() {
      me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType result = me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.valueOf(messageType_);
      return result == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.UNRECOGNIZED : result;
    }

    public static final int SERVICEIDENTIFIER_FIELD_NUMBER = 11;
    private me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier serviceIdentifier_;
    /**
     * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    public boolean hasServiceIdentifier() {
      return serviceIdentifier_ != null;
    }
    /**
     * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getServiceIdentifier() {
      return serviceIdentifier_ == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance() : serviceIdentifier_;
    }
    /**
     * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder getServiceIdentifierOrBuilder() {
      return getServiceIdentifier();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 16;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 16;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageIdentifier_ != 0L) {
        output.writeInt64(1, messageIdentifier_);
      }
      if (messageType_ != me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.MESSAGE_TYPE_NONE.getNumber()) {
        output.writeEnum(2, messageType_);
      }
      if (serviceIdentifier_ != null) {
        output.writeMessage(11, getServiceIdentifier());
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(16, payload_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageIdentifier_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageIdentifier_);
      }
      if (messageType_ != me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.MESSAGE_TYPE_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (serviceIdentifier_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getServiceIdentifier());
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, payload_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket)) {
        return super.equals(obj);
      }
      me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket other = (me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket) obj;

      boolean result = true;
      result = result && (getMessageIdentifier()
          == other.getMessageIdentifier());
      result = result && messageType_ == other.messageType_;
      result = result && (hasServiceIdentifier() == other.hasServiceIdentifier());
      if (hasServiceIdentifier()) {
        result = result && getServiceIdentifier()
            .equals(other.getServiceIdentifier());
      }
      result = result && getPayload()
          .equals(other.getPayload());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageIdentifier());
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      if (hasServiceIdentifier()) {
        hash = (37 * hash) + SERVICEIDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getServiceIdentifier().hashCode();
      }
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.trinopoty.protobufRpc.codec.WirePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.trinopoty.protobufRpc.codec.WirePacket)
        me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.Builder.class);
      }

      // Construct using me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageIdentifier_ = 0L;

        messageType_ = 0;

        if (serviceIdentifierBuilder_ == null) {
          serviceIdentifier_ = null;
        } else {
          serviceIdentifier_ = null;
          serviceIdentifierBuilder_ = null;
        }
        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket getDefaultInstanceForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.getDefaultInstance();
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket build() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket buildPartial() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket result = new me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket(this);
        result.messageIdentifier_ = messageIdentifier_;
        result.messageType_ = messageType_;
        if (serviceIdentifierBuilder_ == null) {
          result.serviceIdentifier_ = serviceIdentifier_;
        } else {
          result.serviceIdentifier_ = serviceIdentifierBuilder_.build();
        }
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket) {
          return mergeFrom((me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket other) {
        if (other == me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.getDefaultInstance()) return this;
        if (other.getMessageIdentifier() != 0L) {
          setMessageIdentifier(other.getMessageIdentifier());
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.hasServiceIdentifier()) {
          mergeServiceIdentifier(other.getServiceIdentifier());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long messageIdentifier_ ;
      /**
       * <code>int64 messageIdentifier = 1;</code>
       */
      public long getMessageIdentifier() {
        return messageIdentifier_;
      }
      /**
       * <code>int64 messageIdentifier = 1;</code>
       */
      public Builder setMessageIdentifier(long value) {
        
        messageIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageIdentifier = 1;</code>
       */
      public Builder clearMessageIdentifier() {
        
        messageIdentifier_ = 0L;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType getMessageType() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType result = me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.valueOf(messageType_);
        return result == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public Builder setMessageType(me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier serviceIdentifier_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder> serviceIdentifierBuilder_;
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public boolean hasServiceIdentifier() {
        return serviceIdentifierBuilder_ != null || serviceIdentifier_ != null;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getServiceIdentifier() {
        if (serviceIdentifierBuilder_ == null) {
          return serviceIdentifier_ == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance() : serviceIdentifier_;
        } else {
          return serviceIdentifierBuilder_.getMessage();
        }
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public Builder setServiceIdentifier(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier value) {
        if (serviceIdentifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serviceIdentifier_ = value;
          onChanged();
        } else {
          serviceIdentifierBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public Builder setServiceIdentifier(
          me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder builderForValue) {
        if (serviceIdentifierBuilder_ == null) {
          serviceIdentifier_ = builderForValue.build();
          onChanged();
        } else {
          serviceIdentifierBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public Builder mergeServiceIdentifier(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier value) {
        if (serviceIdentifierBuilder_ == null) {
          if (serviceIdentifier_ != null) {
            serviceIdentifier_ =
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.newBuilder(serviceIdentifier_).mergeFrom(value).buildPartial();
          } else {
            serviceIdentifier_ = value;
          }
          onChanged();
        } else {
          serviceIdentifierBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public Builder clearServiceIdentifier() {
        if (serviceIdentifierBuilder_ == null) {
          serviceIdentifier_ = null;
          onChanged();
        } else {
          serviceIdentifier_ = null;
          serviceIdentifierBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder getServiceIdentifierBuilder() {
        
        onChanged();
        return getServiceIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder getServiceIdentifierOrBuilder() {
        if (serviceIdentifierBuilder_ != null) {
          return serviceIdentifierBuilder_.getMessageOrBuilder();
        } else {
          return serviceIdentifier_ == null ?
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance() : serviceIdentifier_;
        }
      }
      /**
       * <code>.me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder> 
          getServiceIdentifierFieldBuilder() {
        if (serviceIdentifierBuilder_ == null) {
          serviceIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder>(
                  getServiceIdentifier(),
                  getParentForChildren(),
                  isClean());
          serviceIdentifier_ = null;
        }
        return serviceIdentifierBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 16;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 16;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 16;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:me.trinopoty.protobufRpc.codec.WirePacket)
    }

    // @@protoc_insertion_point(class_scope:me.trinopoty.protobufRpc.codec.WirePacket)
    private static final me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket();
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WirePacket>
        PARSER = new com.google.protobuf.AbstractParser<WirePacket>() {
      public WirePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WirePacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WirePacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WirePacket> getParserForType() {
      return PARSER;
    }

    public me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.trinopoty.protobufRpc.codec.ErrorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code me.trinopoty.protobufRpc.codec.ErrorMessage}
   */
  public  static final class ErrorMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.trinopoty.protobufRpc.codec.ErrorMessage)
      ErrorMessageOrBuilder {
    // Use ErrorMessage.newBuilder() to construct.
    private ErrorMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorMessage() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ErrorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage)) {
        return super.equals(obj);
      }
      me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage other = (me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.trinopoty.protobufRpc.codec.ErrorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.trinopoty.protobufRpc.codec.ErrorMessage)
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.Builder.class);
      }

      // Construct using me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage getDefaultInstanceForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.getDefaultInstance();
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage build() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage buildPartial() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage result = new me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage) {
          return mergeFrom((me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage other) {
        if (other == me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:me.trinopoty.protobufRpc.codec.ErrorMessage)
    }

    // @@protoc_insertion_point(class_scope:me.trinopoty.protobufRpc.codec.ErrorMessage)
    private static final me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage();
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorMessage>
        PARSER = new com.google.protobuf.AbstractParser<ErrorMessage>() {
      public ErrorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ErrorMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorMessage> getParserForType() {
      return PARSER;
    }

    public me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_trinopoty_protobufRpc_codec_WirePacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/me/trinopoty/protobufRpc/codec/WirePac" +
      "ket.proto\022\036me.trinopoty.protobufRpc.code" +
      "c\"H\n\021ServiceIdentifier\022\031\n\021serviceIdentif" +
      "ier\030\001 \001(\005\022\030\n\020methodIdentifier\030\002 \001(\005\"\310\001\n\n" +
      "WirePacket\022\031\n\021messageIdentifier\030\001 \001(\003\022@\n" +
      "\013messageType\030\002 \001(\0162+.me.trinopoty.protob" +
      "ufRpc.codec.MessageType\022L\n\021serviceIdenti" +
      "fier\030\013 \001(\01321.me.trinopoty.protobufRpc.co" +
      "dec.ServiceIdentifier\022\017\n\007payload\030\020 \001(\014\"\037" +
      "\n\014ErrorMessage\022\017\n\007message\030\001 \001(\t*q\n\013Messa",
      "geType\022\025\n\021MESSAGE_TYPE_NONE\020\000\022\030\n\024MESSAGE" +
      "_TYPE_REQUEST\020\001\022\031\n\025MESSAGE_TYPE_RESPONSE" +
      "\020\002\022\026\n\022MESSAGE_TYPE_ERROR\020\003B\022B\020WirePacket" +
      "Formatb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor,
        new java.lang.String[] { "ServiceIdentifier", "MethodIdentifier", });
    internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_trinopoty_protobufRpc_codec_WirePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor,
        new java.lang.String[] { "MessageIdentifier", "MessageType", "ServiceIdentifier", "Payload", });
    internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
