// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: me/trinopoty/protobufRpc/codec/WirePacket.proto

package me.trinopoty.protobufRpc.codec;

public final class WirePacketFormat {
  private WirePacketFormat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code me.trinopoty.protobufRpc.codec.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MESSAGE_TYPE_NONE = 0;</code>
     */
    MESSAGE_TYPE_NONE(0),
    /**
     * <code>MESSAGE_TYPE_REQUEST = 1;</code>
     */
    MESSAGE_TYPE_REQUEST(1),
    /**
     * <code>MESSAGE_TYPE_RESPONSE = 2;</code>
     */
    MESSAGE_TYPE_RESPONSE(2),
    /**
     * <code>MESSAGE_TYPE_ERROR = 3;</code>
     */
    MESSAGE_TYPE_ERROR(3),
    /**
     * <code>MESSAGE_TYPE_OOB = 4;</code>
     */
    MESSAGE_TYPE_OOB(4),
    /**
     * <code>MESSAGE_TYPE_KEEP_ALIVE = 5;</code>
     */
    MESSAGE_TYPE_KEEP_ALIVE(5),
    ;

    /**
     * <code>MESSAGE_TYPE_NONE = 0;</code>
     */
    public static final int MESSAGE_TYPE_NONE_VALUE = 0;
    /**
     * <code>MESSAGE_TYPE_REQUEST = 1;</code>
     */
    public static final int MESSAGE_TYPE_REQUEST_VALUE = 1;
    /**
     * <code>MESSAGE_TYPE_RESPONSE = 2;</code>
     */
    public static final int MESSAGE_TYPE_RESPONSE_VALUE = 2;
    /**
     * <code>MESSAGE_TYPE_ERROR = 3;</code>
     */
    public static final int MESSAGE_TYPE_ERROR_VALUE = 3;
    /**
     * <code>MESSAGE_TYPE_OOB = 4;</code>
     */
    public static final int MESSAGE_TYPE_OOB_VALUE = 4;
    /**
     * <code>MESSAGE_TYPE_KEEP_ALIVE = 5;</code>
     */
    public static final int MESSAGE_TYPE_KEEP_ALIVE_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return MESSAGE_TYPE_NONE;
        case 1: return MESSAGE_TYPE_REQUEST;
        case 2: return MESSAGE_TYPE_RESPONSE;
        case 3: return MESSAGE_TYPE_ERROR;
        case 4: return MESSAGE_TYPE_OOB;
        case 5: return MESSAGE_TYPE_KEEP_ALIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:me.trinopoty.protobufRpc.codec.MessageType)
  }

  public interface ServiceIdentifierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 serviceIdentifier = 1;</code>
     */
    boolean hasServiceIdentifier();
    /**
     * <code>required int32 serviceIdentifier = 1;</code>
     */
    int getServiceIdentifier();

    /**
     * <code>required int32 methodIdentifier = 2;</code>
     */
    boolean hasMethodIdentifier();
    /**
     * <code>required int32 methodIdentifier = 2;</code>
     */
    int getMethodIdentifier();
  }
  /**
   * Protobuf type {@code me.trinopoty.protobufRpc.codec.ServiceIdentifier}
   */
  public  static final class ServiceIdentifier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
      ServiceIdentifierOrBuilder {
    // Use ServiceIdentifier.newBuilder() to construct.
    private ServiceIdentifier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceIdentifier() {
      serviceIdentifier_ = 0;
      methodIdentifier_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceIdentifier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serviceIdentifier_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              methodIdentifier_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder.class);
    }

    private int bitField0_;
    public static final int SERVICEIDENTIFIER_FIELD_NUMBER = 1;
    private int serviceIdentifier_;
    /**
     * <code>required int32 serviceIdentifier = 1;</code>
     */
    public boolean hasServiceIdentifier() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serviceIdentifier = 1;</code>
     */
    public int getServiceIdentifier() {
      return serviceIdentifier_;
    }

    public static final int METHODIDENTIFIER_FIELD_NUMBER = 2;
    private int methodIdentifier_;
    /**
     * <code>required int32 methodIdentifier = 2;</code>
     */
    public boolean hasMethodIdentifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 methodIdentifier = 2;</code>
     */
    public int getMethodIdentifier() {
      return methodIdentifier_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServiceIdentifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodIdentifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serviceIdentifier_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, methodIdentifier_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serviceIdentifier_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, methodIdentifier_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier)) {
        return super.equals(obj);
      }
      me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier other = (me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier) obj;

      boolean result = true;
      result = result && (hasServiceIdentifier() == other.hasServiceIdentifier());
      if (hasServiceIdentifier()) {
        result = result && (getServiceIdentifier()
            == other.getServiceIdentifier());
      }
      result = result && (hasMethodIdentifier() == other.hasMethodIdentifier());
      if (hasMethodIdentifier()) {
        result = result && (getMethodIdentifier()
            == other.getMethodIdentifier());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServiceIdentifier()) {
        hash = (37 * hash) + SERVICEIDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getServiceIdentifier();
      }
      if (hasMethodIdentifier()) {
        hash = (37 * hash) + METHODIDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getMethodIdentifier();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.trinopoty.protobufRpc.codec.ServiceIdentifier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder.class);
      }

      // Construct using me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serviceIdentifier_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        methodIdentifier_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getDefaultInstanceForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance();
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier build() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier buildPartial() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier result = new me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceIdentifier_ = serviceIdentifier_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodIdentifier_ = methodIdentifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier) {
          return mergeFrom((me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier other) {
        if (other == me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance()) return this;
        if (other.hasServiceIdentifier()) {
          setServiceIdentifier(other.getServiceIdentifier());
        }
        if (other.hasMethodIdentifier()) {
          setMethodIdentifier(other.getMethodIdentifier());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceIdentifier()) {
          return false;
        }
        if (!hasMethodIdentifier()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serviceIdentifier_ ;
      /**
       * <code>required int32 serviceIdentifier = 1;</code>
       */
      public boolean hasServiceIdentifier() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serviceIdentifier = 1;</code>
       */
      public int getServiceIdentifier() {
        return serviceIdentifier_;
      }
      /**
       * <code>required int32 serviceIdentifier = 1;</code>
       */
      public Builder setServiceIdentifier(int value) {
        bitField0_ |= 0x00000001;
        serviceIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serviceIdentifier = 1;</code>
       */
      public Builder clearServiceIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceIdentifier_ = 0;
        onChanged();
        return this;
      }

      private int methodIdentifier_ ;
      /**
       * <code>required int32 methodIdentifier = 2;</code>
       */
      public boolean hasMethodIdentifier() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 methodIdentifier = 2;</code>
       */
      public int getMethodIdentifier() {
        return methodIdentifier_;
      }
      /**
       * <code>required int32 methodIdentifier = 2;</code>
       */
      public Builder setMethodIdentifier(int value) {
        bitField0_ |= 0x00000002;
        methodIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 methodIdentifier = 2;</code>
       */
      public Builder clearMethodIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodIdentifier_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
    }

    // @@protoc_insertion_point(class_scope:me.trinopoty.protobufRpc.codec.ServiceIdentifier)
    private static final me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier();
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ServiceIdentifier>
        PARSER = new com.google.protobuf.AbstractParser<ServiceIdentifier>() {
      public ServiceIdentifier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServiceIdentifier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceIdentifier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceIdentifier> getParserForType() {
      return PARSER;
    }

    public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WirePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.trinopoty.protobufRpc.codec.WirePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 messageIdentifier = 1 [default = 0];</code>
     */
    boolean hasMessageIdentifier();
    /**
     * <code>optional int64 messageIdentifier = 1 [default = 0];</code>
     */
    long getMessageIdentifier();

    /**
     * <code>required .me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
     */
    boolean hasMessageType();
    /**
     * <code>required .me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
     */
    me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType getMessageType();

    /**
     * <code>optional int32 crc32 = 3;</code>
     */
    boolean hasCrc32();
    /**
     * <code>optional int32 crc32 = 3;</code>
     */
    int getCrc32();

    /**
     * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    boolean hasServiceIdentifier();
    /**
     * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getServiceIdentifier();
    /**
     * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder getServiceIdentifierOrBuilder();

    /**
     * <code>optional bytes payload = 16;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional bytes payload = 16;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code me.trinopoty.protobufRpc.codec.WirePacket}
   */
  public  static final class WirePacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.trinopoty.protobufRpc.codec.WirePacket)
      WirePacketOrBuilder {
    // Use WirePacket.newBuilder() to construct.
    private WirePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WirePacket() {
      messageIdentifier_ = 0L;
      messageType_ = 0;
      crc32_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WirePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageIdentifier_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType value = me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                messageType_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              crc32_ = input.readInt32();
              break;
            }
            case 90: {
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = serviceIdentifier_.toBuilder();
              }
              serviceIdentifier_ = input.readMessage(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serviceIdentifier_);
                serviceIdentifier_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 130: {
              bitField0_ |= 0x00000010;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGEIDENTIFIER_FIELD_NUMBER = 1;
    private long messageIdentifier_;
    /**
     * <code>optional int64 messageIdentifier = 1 [default = 0];</code>
     */
    public boolean hasMessageIdentifier() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 messageIdentifier = 1 [default = 0];</code>
     */
    public long getMessageIdentifier() {
      return messageIdentifier_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <code>required .me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
     */
    public me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType getMessageType() {
      me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType result = me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.valueOf(messageType_);
      return result == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.MESSAGE_TYPE_NONE : result;
    }

    public static final int CRC32_FIELD_NUMBER = 3;
    private int crc32_;
    /**
     * <code>optional int32 crc32 = 3;</code>
     */
    public boolean hasCrc32() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 crc32 = 3;</code>
     */
    public int getCrc32() {
      return crc32_;
    }

    public static final int SERVICEIDENTIFIER_FIELD_NUMBER = 11;
    private me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier serviceIdentifier_;
    /**
     * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    public boolean hasServiceIdentifier() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getServiceIdentifier() {
      return serviceIdentifier_ == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance() : serviceIdentifier_;
    }
    /**
     * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
     */
    public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder getServiceIdentifierOrBuilder() {
      return serviceIdentifier_ == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance() : serviceIdentifier_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 16;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 16;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes payload = 16;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasServiceIdentifier()) {
        if (!getServiceIdentifier().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, messageIdentifier_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, messageType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, crc32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(11, getServiceIdentifier());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(16, payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageIdentifier_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, crc32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getServiceIdentifier());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket)) {
        return super.equals(obj);
      }
      me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket other = (me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket) obj;

      boolean result = true;
      result = result && (hasMessageIdentifier() == other.hasMessageIdentifier());
      if (hasMessageIdentifier()) {
        result = result && (getMessageIdentifier()
            == other.getMessageIdentifier());
      }
      result = result && (hasMessageType() == other.hasMessageType());
      if (hasMessageType()) {
        result = result && messageType_ == other.messageType_;
      }
      result = result && (hasCrc32() == other.hasCrc32());
      if (hasCrc32()) {
        result = result && (getCrc32()
            == other.getCrc32());
      }
      result = result && (hasServiceIdentifier() == other.hasServiceIdentifier());
      if (hasServiceIdentifier()) {
        result = result && getServiceIdentifier()
            .equals(other.getServiceIdentifier());
      }
      result = result && (hasPayload() == other.hasPayload());
      if (hasPayload()) {
        result = result && getPayload()
            .equals(other.getPayload());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageIdentifier()) {
        hash = (37 * hash) + MESSAGEIDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMessageIdentifier());
      }
      if (hasMessageType()) {
        hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
        hash = (53 * hash) + messageType_;
      }
      if (hasCrc32()) {
        hash = (37 * hash) + CRC32_FIELD_NUMBER;
        hash = (53 * hash) + getCrc32();
      }
      if (hasServiceIdentifier()) {
        hash = (37 * hash) + SERVICEIDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getServiceIdentifier().hashCode();
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.trinopoty.protobufRpc.codec.WirePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.trinopoty.protobufRpc.codec.WirePacket)
        me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.Builder.class);
      }

      // Construct using me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getServiceIdentifierFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        messageIdentifier_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        crc32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (serviceIdentifierBuilder_ == null) {
          serviceIdentifier_ = null;
        } else {
          serviceIdentifierBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket getDefaultInstanceForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.getDefaultInstance();
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket build() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket buildPartial() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket result = new me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageIdentifier_ = messageIdentifier_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.crc32_ = crc32_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (serviceIdentifierBuilder_ == null) {
          result.serviceIdentifier_ = serviceIdentifier_;
        } else {
          result.serviceIdentifier_ = serviceIdentifierBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket) {
          return mergeFrom((me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket other) {
        if (other == me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket.getDefaultInstance()) return this;
        if (other.hasMessageIdentifier()) {
          setMessageIdentifier(other.getMessageIdentifier());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasCrc32()) {
          setCrc32(other.getCrc32());
        }
        if (other.hasServiceIdentifier()) {
          mergeServiceIdentifier(other.getServiceIdentifier());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageType()) {
          return false;
        }
        if (hasServiceIdentifier()) {
          if (!getServiceIdentifier().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long messageIdentifier_ ;
      /**
       * <code>optional int64 messageIdentifier = 1 [default = 0];</code>
       */
      public boolean hasMessageIdentifier() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 messageIdentifier = 1 [default = 0];</code>
       */
      public long getMessageIdentifier() {
        return messageIdentifier_;
      }
      /**
       * <code>optional int64 messageIdentifier = 1 [default = 0];</code>
       */
      public Builder setMessageIdentifier(long value) {
        bitField0_ |= 0x00000001;
        messageIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 messageIdentifier = 1 [default = 0];</code>
       */
      public Builder clearMessageIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageIdentifier_ = 0L;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>required .me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType getMessageType() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType result = me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.valueOf(messageType_);
        return result == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType.MESSAGE_TYPE_NONE : result;
      }
      /**
       * <code>required .me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public Builder setMessageType(me.trinopoty.protobufRpc.codec.WirePacketFormat.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .me.trinopoty.protobufRpc.codec.MessageType messageType = 2;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int crc32_ ;
      /**
       * <code>optional int32 crc32 = 3;</code>
       */
      public boolean hasCrc32() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 crc32 = 3;</code>
       */
      public int getCrc32() {
        return crc32_;
      }
      /**
       * <code>optional int32 crc32 = 3;</code>
       */
      public Builder setCrc32(int value) {
        bitField0_ |= 0x00000004;
        crc32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 crc32 = 3;</code>
       */
      public Builder clearCrc32() {
        bitField0_ = (bitField0_ & ~0x00000004);
        crc32_ = 0;
        onChanged();
        return this;
      }

      private me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier serviceIdentifier_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder> serviceIdentifierBuilder_;
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public boolean hasServiceIdentifier() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier getServiceIdentifier() {
        if (serviceIdentifierBuilder_ == null) {
          return serviceIdentifier_ == null ? me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance() : serviceIdentifier_;
        } else {
          return serviceIdentifierBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public Builder setServiceIdentifier(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier value) {
        if (serviceIdentifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serviceIdentifier_ = value;
          onChanged();
        } else {
          serviceIdentifierBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public Builder setServiceIdentifier(
          me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder builderForValue) {
        if (serviceIdentifierBuilder_ == null) {
          serviceIdentifier_ = builderForValue.build();
          onChanged();
        } else {
          serviceIdentifierBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public Builder mergeServiceIdentifier(me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier value) {
        if (serviceIdentifierBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              serviceIdentifier_ != null &&
              serviceIdentifier_ != me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance()) {
            serviceIdentifier_ =
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.newBuilder(serviceIdentifier_).mergeFrom(value).buildPartial();
          } else {
            serviceIdentifier_ = value;
          }
          onChanged();
        } else {
          serviceIdentifierBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public Builder clearServiceIdentifier() {
        if (serviceIdentifierBuilder_ == null) {
          serviceIdentifier_ = null;
          onChanged();
        } else {
          serviceIdentifierBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder getServiceIdentifierBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getServiceIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder getServiceIdentifierOrBuilder() {
        if (serviceIdentifierBuilder_ != null) {
          return serviceIdentifierBuilder_.getMessageOrBuilder();
        } else {
          return serviceIdentifier_ == null ?
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.getDefaultInstance() : serviceIdentifier_;
        }
      }
      /**
       * <code>optional .me.trinopoty.protobufRpc.codec.ServiceIdentifier serviceIdentifier = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder> 
          getServiceIdentifierFieldBuilder() {
        if (serviceIdentifierBuilder_ == null) {
          serviceIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifier.Builder, me.trinopoty.protobufRpc.codec.WirePacketFormat.ServiceIdentifierOrBuilder>(
                  getServiceIdentifier(),
                  getParentForChildren(),
                  isClean());
          serviceIdentifier_ = null;
        }
        return serviceIdentifierBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 16;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes payload = 16;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 16;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payload = 16;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000010);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.trinopoty.protobufRpc.codec.WirePacket)
    }

    // @@protoc_insertion_point(class_scope:me.trinopoty.protobufRpc.codec.WirePacket)
    private static final me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket();
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WirePacket>
        PARSER = new com.google.protobuf.AbstractParser<WirePacket>() {
      public WirePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WirePacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WirePacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WirePacket> getParserForType() {
      return PARSER;
    }

    public me.trinopoty.protobufRpc.codec.WirePacketFormat.WirePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.trinopoty.protobufRpc.codec.ErrorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code me.trinopoty.protobufRpc.codec.ErrorMessage}
   */
  public  static final class ErrorMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.trinopoty.protobufRpc.codec.ErrorMessage)
      ErrorMessageOrBuilder {
    // Use ErrorMessage.newBuilder() to construct.
    private ErrorMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorMessage() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>required string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage)) {
        return super.equals(obj);
      }
      me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage other = (me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage) obj;

      boolean result = true;
      result = result && (hasMessage() == other.hasMessage());
      if (hasMessage()) {
        result = result && getMessage()
            .equals(other.getMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.trinopoty.protobufRpc.codec.ErrorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.trinopoty.protobufRpc.codec.ErrorMessage)
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.class, me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.Builder.class);
      }

      // Construct using me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage getDefaultInstanceForType() {
        return me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.getDefaultInstance();
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage build() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage buildPartial() {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage result = new me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage) {
          return mergeFrom((me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage other) {
        if (other == me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.trinopoty.protobufRpc.codec.ErrorMessage)
    }

    // @@protoc_insertion_point(class_scope:me.trinopoty.protobufRpc.codec.ErrorMessage)
    private static final me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage();
    }

    public static me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ErrorMessage>
        PARSER = new com.google.protobuf.AbstractParser<ErrorMessage>() {
      public ErrorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ErrorMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorMessage> getParserForType() {
      return PARSER;
    }

    public me.trinopoty.protobufRpc.codec.WirePacketFormat.ErrorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_trinopoty_protobufRpc_codec_WirePacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/me/trinopoty/protobufRpc/codec/WirePac" +
      "ket.proto\022\036me.trinopoty.protobufRpc.code" +
      "c\"H\n\021ServiceIdentifier\022\031\n\021serviceIdentif" +
      "ier\030\001 \002(\005\022\030\n\020methodIdentifier\030\002 \002(\005\"\332\001\n\n" +
      "WirePacket\022\034\n\021messageIdentifier\030\001 \001(\003:\0010" +
      "\022@\n\013messageType\030\002 \002(\0162+.me.trinopoty.pro" +
      "tobufRpc.codec.MessageType\022\r\n\005crc32\030\003 \001(" +
      "\005\022L\n\021serviceIdentifier\030\013 \001(\01321.me.trinop" +
      "oty.protobufRpc.codec.ServiceIdentifier\022" +
      "\017\n\007payload\030\020 \001(\014\"\037\n\014ErrorMessage\022\017\n\007mess",
      "age\030\001 \002(\t*\244\001\n\013MessageType\022\025\n\021MESSAGE_TYP" +
      "E_NONE\020\000\022\030\n\024MESSAGE_TYPE_REQUEST\020\001\022\031\n\025ME" +
      "SSAGE_TYPE_RESPONSE\020\002\022\026\n\022MESSAGE_TYPE_ER" +
      "ROR\020\003\022\024\n\020MESSAGE_TYPE_OOB\020\004\022\033\n\027MESSAGE_T" +
      "YPE_KEEP_ALIVE\020\005B\022B\020WirePacketFormat"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_trinopoty_protobufRpc_codec_ServiceIdentifier_descriptor,
        new java.lang.String[] { "ServiceIdentifier", "MethodIdentifier", });
    internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_trinopoty_protobufRpc_codec_WirePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_trinopoty_protobufRpc_codec_WirePacket_descriptor,
        new java.lang.String[] { "MessageIdentifier", "MessageType", "Crc32", "ServiceIdentifier", "Payload", });
    internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_trinopoty_protobufRpc_codec_ErrorMessage_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
